<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobs/v1/jobs.proto

namespace RoadRunner\Jobs\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Stat used as a response for the Stats RPC call
 *
 * Generated from protobuf message <code>jobs.v1.Stat</code>
 */
class Stat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string pipeline = 1 [json_name = "pipeline"];</code>
     */
    protected $pipeline = '';
    /**
     * Generated from protobuf field <code>string driver = 2 [json_name = "driver"];</code>
     */
    protected $driver = '';
    /**
     * Generated from protobuf field <code>string queue = 3 [json_name = "queue"];</code>
     */
    protected $queue = '';
    /**
     * Generated from protobuf field <code>int64 active = 4 [json_name = "active"];</code>
     */
    protected $active = 0;
    /**
     * Generated from protobuf field <code>int64 delayed = 5 [json_name = "delayed"];</code>
     */
    protected $delayed = 0;
    /**
     * Generated from protobuf field <code>int64 reserved = 6 [json_name = "reserved"];</code>
     */
    protected $reserved = 0;
    /**
     * Generated from protobuf field <code>bool ready = 7 [json_name = "ready"];</code>
     */
    protected $ready = false;
    /**
     * new in 2.10.5
     *
     * Generated from protobuf field <code>uint64 priority = 8 [json_name = "priority"];</code>
     */
    protected $priority = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pipeline
     *     @type string $driver
     *     @type string $queue
     *     @type int|string $active
     *     @type int|string $delayed
     *     @type int|string $reserved
     *     @type bool $ready
     *     @type int|string $priority
     *           new in 2.10.5
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Jobs\DTO\V1\GPBMetadata\Jobs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string pipeline = 1 [json_name = "pipeline"];</code>
     * @return string
     */
    public function getPipeline()
    {
        return $this->pipeline;
    }

    /**
     * Generated from protobuf field <code>string pipeline = 1 [json_name = "pipeline"];</code>
     * @param string $var
     * @return $this
     */
    public function setPipeline($var)
    {
        GPBUtil::checkString($var, True);
        $this->pipeline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string driver = 2 [json_name = "driver"];</code>
     * @return string
     */
    public function getDriver()
    {
        return $this->driver;
    }

    /**
     * Generated from protobuf field <code>string driver = 2 [json_name = "driver"];</code>
     * @param string $var
     * @return $this
     */
    public function setDriver($var)
    {
        GPBUtil::checkString($var, True);
        $this->driver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string queue = 3 [json_name = "queue"];</code>
     * @return string
     */
    public function getQueue()
    {
        return $this->queue;
    }

    /**
     * Generated from protobuf field <code>string queue = 3 [json_name = "queue"];</code>
     * @param string $var
     * @return $this
     */
    public function setQueue($var)
    {
        GPBUtil::checkString($var, True);
        $this->queue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 active = 4 [json_name = "active"];</code>
     * @return int|string
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Generated from protobuf field <code>int64 active = 4 [json_name = "active"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkInt64($var);
        $this->active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 delayed = 5 [json_name = "delayed"];</code>
     * @return int|string
     */
    public function getDelayed()
    {
        return $this->delayed;
    }

    /**
     * Generated from protobuf field <code>int64 delayed = 5 [json_name = "delayed"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelayed($var)
    {
        GPBUtil::checkInt64($var);
        $this->delayed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reserved = 6 [json_name = "reserved"];</code>
     * @return int|string
     */
    public function getReserved()
    {
        return $this->reserved;
    }

    /**
     * Generated from protobuf field <code>int64 reserved = 6 [json_name = "reserved"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setReserved($var)
    {
        GPBUtil::checkInt64($var);
        $this->reserved = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ready = 7 [json_name = "ready"];</code>
     * @return bool
     */
    public function getReady()
    {
        return $this->ready;
    }

    /**
     * Generated from protobuf field <code>bool ready = 7 [json_name = "ready"];</code>
     * @param bool $var
     * @return $this
     */
    public function setReady($var)
    {
        GPBUtil::checkBool($var);
        $this->ready = $var;

        return $this;
    }

    /**
     * new in 2.10.5
     *
     * Generated from protobuf field <code>uint64 priority = 8 [json_name = "priority"];</code>
     * @return int|string
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * new in 2.10.5
     *
     * Generated from protobuf field <code>uint64 priority = 8 [json_name = "priority"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkUint64($var);
        $this->priority = $var;

        return $this;
    }

}

