<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http/v1beta/http.proto

namespace RoadRunner\HTTP\DTO\V1BETA1\GPBMetadata;

class Http
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            '
ç	
http/v1beta/http.protohttp.v1beta"–
Request
remote_addr (	R
remoteAddr
protocol (	Rprotocol
method (	Rmethod
uri (	Ruri8
header (2 .http.v1beta.Request.HeaderEntryRheader;
cookies (2!.http.v1beta.Request.CookiesEntryRcookies
	raw_query (	RrawQuery
parsed (RparsedD

attributes	 (2$.http.v1beta.Request.AttributesEntryR
attributes.
uploads
 (2.http.v1beta.UploadsRuploadsS
HeaderEntry
key (	Rkey.
value (2.http.v1beta.HeaderValueRvalue:8T
CookiesEntry
key (	Rkey.
value (2.http.v1beta.HeaderValueRvalue:8W
AttributesEntry
key (	Rkey.
value (2.http.v1beta.HeaderValueRvalue:8"¶
Response
status (Rstatus<
headers (2".http.v1beta.Response.HeadersEntryRheadersT
HeadersEntry
key (	Rkey.
value (2.http.v1beta.HeaderValueRvalue:8"6
Uploads+
list (2.http.v1beta.FileUploadRlist"±

FileUpload
name (	Rname
mime (	Rmime
size (Rsize
error (Rerror#
temp_filename (	RtempFilename,
header	 (2.google.protobuf.AnyRheader"#
HeaderValue
value (	RvalueBUZhttp/v1betaÊRoadRunner\\HTTP\\DTO\\V1BETA1â\'RoadRunner\\HTTP\\DTO\\V1BETA1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

