<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centrifugo/proxy/v1/proxy.proto

namespace RoadRunner\Centrifugal\Proxy\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.proxy.ConnectResult</code>
 */
class ConnectResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user = 1 [json_name = "user"];</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>int64 expire_at = 2 [json_name = "expireAt"];</code>
     */
    protected $expire_at = 0;
    /**
     * Generated from protobuf field <code>bytes info = 3 [json_name = "info"];</code>
     */
    protected $info = '';
    /**
     * Generated from protobuf field <code>string b64info = 4 [json_name = "b64info"];</code>
     */
    protected $b64info = '';
    /**
     * Generated from protobuf field <code>bytes data = 5 [json_name = "data"];</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>string b64data = 6 [json_name = "b64data"];</code>
     */
    protected $b64data = '';
    /**
     * Generated from protobuf field <code>repeated string channels = 7 [json_name = "channels"];</code>
     */
    private $channels;
    /**
     * Generated from protobuf field <code>map<string, .centrifugal.centrifugo.proxy.SubscribeOptions> subs = 8 [json_name = "subs"];</code>
     */
    private $subs;
    /**
     * Generated from protobuf field <code>bytes meta = 9 [json_name = "meta"];</code>
     */
    protected $meta = '';
    /**
     * Generated from protobuf field <code>repeated .centrifugal.centrifugo.proxy.ChannelsCapability caps = 10 [json_name = "caps"];</code>
     */
    private $caps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user
     *     @type int|string $expire_at
     *     @type string $info
     *     @type string $b64info
     *     @type string $data
     *     @type string $b64data
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $channels
     *     @type array|\Google\Protobuf\Internal\MapField $subs
     *     @type string $meta
     *     @type array<\RoadRunner\Centrifugal\Proxy\DTO\V1\ChannelsCapability>|\Google\Protobuf\Internal\RepeatedField $caps
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\Proxy\DTO\V1\GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user = 1 [json_name = "user"];</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 1 [json_name = "user"];</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expire_at = 2 [json_name = "expireAt"];</code>
     * @return int|string
     */
    public function getExpireAt()
    {
        return $this->expire_at;
    }

    /**
     * Generated from protobuf field <code>int64 expire_at = 2 [json_name = "expireAt"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes info = 3 [json_name = "info"];</code>
     * @return string
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>bytes info = 3 [json_name = "info"];</code>
     * @param string $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkString($var, False);
        $this->info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b64info = 4 [json_name = "b64info"];</code>
     * @return string
     */
    public function getB64Info()
    {
        return $this->b64info;
    }

    /**
     * Generated from protobuf field <code>string b64info = 4 [json_name = "b64info"];</code>
     * @param string $var
     * @return $this
     */
    public function setB64Info($var)
    {
        GPBUtil::checkString($var, True);
        $this->b64info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 5 [json_name = "data"];</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 5 [json_name = "data"];</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b64data = 6 [json_name = "b64data"];</code>
     * @return string
     */
    public function getB64Data()
    {
        return $this->b64data;
    }

    /**
     * Generated from protobuf field <code>string b64data = 6 [json_name = "b64data"];</code>
     * @param string $var
     * @return $this
     */
    public function setB64Data($var)
    {
        GPBUtil::checkString($var, True);
        $this->b64data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string channels = 7 [json_name = "channels"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChannels()
    {
        return $this->channels;
    }

    /**
     * Generated from protobuf field <code>repeated string channels = 7 [json_name = "channels"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChannels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->channels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .centrifugal.centrifugo.proxy.SubscribeOptions> subs = 8 [json_name = "subs"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSubs()
    {
        return $this->subs;
    }

    /**
     * Generated from protobuf field <code>map<string, .centrifugal.centrifugo.proxy.SubscribeOptions> subs = 8 [json_name = "subs"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSubs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\Centrifugal\Proxy\DTO\V1\SubscribeOptions::class);
        $this->subs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes meta = 9 [json_name = "meta"];</code>
     * @return string
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>bytes meta = 9 [json_name = "meta"];</code>
     * @param string $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkString($var, False);
        $this->meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .centrifugal.centrifugo.proxy.ChannelsCapability caps = 10 [json_name = "caps"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCaps()
    {
        return $this->caps;
    }

    /**
     * Generated from protobuf field <code>repeated .centrifugal.centrifugo.proxy.ChannelsCapability caps = 10 [json_name = "caps"];</code>
     * @param array<\RoadRunner\Centrifugal\Proxy\DTO\V1\ChannelsCapability>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCaps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\Centrifugal\Proxy\DTO\V1\ChannelsCapability::class);
        $this->caps = $arr;

        return $this;
    }

}

