<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centrifugo/proxy/v1/proxy.proto

namespace RoadRunner\Centrifugal\Proxy\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.proxy.PublishResult</code>
 */
class PublishResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes data = 1 [json_name = "data"];</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>string b64data = 2 [json_name = "b64data"];</code>
     */
    protected $b64data = '';
    /**
     * Generated from protobuf field <code>bool skip_history = 3 [json_name = "skipHistory"];</code>
     */
    protected $skip_history = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $data
     *     @type string $b64data
     *     @type bool $skip_history
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\Proxy\DTO\V1\GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes data = 1 [json_name = "data"];</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 1 [json_name = "data"];</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b64data = 2 [json_name = "b64data"];</code>
     * @return string
     */
    public function getB64Data()
    {
        return $this->b64data;
    }

    /**
     * Generated from protobuf field <code>string b64data = 2 [json_name = "b64data"];</code>
     * @param string $var
     * @return $this
     */
    public function setB64Data($var)
    {
        GPBUtil::checkString($var, True);
        $this->b64data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool skip_history = 3 [json_name = "skipHistory"];</code>
     * @return bool
     */
    public function getSkipHistory()
    {
        return $this->skip_history;
    }

    /**
     * Generated from protobuf field <code>bool skip_history = 3 [json_name = "skipHistory"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSkipHistory($var)
    {
        GPBUtil::checkBool($var);
        $this->skip_history = $var;

        return $this;
    }

}

