<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centrifugo/proxy/v1/proxy.proto

namespace RoadRunner\Centrifugal\Proxy\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.proxy.RefreshRequest</code>
 */
class RefreshRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     */
    protected $client = '';
    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     */
    protected $transport = '';
    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     */
    protected $protocol = '';
    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     */
    protected $encoding = '';
    /**
     * Generated from protobuf field <code>string user = 10 [json_name = "user"];</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>bytes meta = 11 [json_name = "meta"];</code>
     */
    protected $meta = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client
     *     @type string $transport
     *     @type string $protocol
     *     @type string $encoding
     *     @type string $user
     *     @type string $meta
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\Proxy\DTO\V1\GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     * @param string $var
     * @return $this
     */
    public function setClient($var)
    {
        GPBUtil::checkString($var, True);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     * @return string
     */
    public function getTransport()
    {
        return $this->transport;
    }

    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransport($var)
    {
        GPBUtil::checkString($var, True);
        $this->transport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     * @return string
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkString($var, True);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     * @return string
     */
    public function getEncoding()
    {
        return $this->encoding;
    }

    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     * @param string $var
     * @return $this
     */
    public function setEncoding($var)
    {
        GPBUtil::checkString($var, True);
        $this->encoding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 10 [json_name = "user"];</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 10 [json_name = "user"];</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes meta = 11 [json_name = "meta"];</code>
     * @return string
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>bytes meta = 11 [json_name = "meta"];</code>
     * @param string $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkString($var, False);
        $this->meta = $var;

        return $this;
    }

}

