<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status/v1beta1/status.proto

namespace RoadRunner\Status\DTO\V1BETA1\GPBMetadata;

class Status
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ð
status/v1beta1/status.protostatus.v1beta1"!
Request
plugin (	Rplugin"8
Response
code (Rcode
message (	RmessageB\\Zstatus/v1beta1ÊRoadRunner\\Status\\DTO\\V1BETA1â)RoadRunner\\Status\\DTO\\V1BETA1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

