<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/v1/service.proto

namespace RoadRunner\Service\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>service.v1.Status</code>
 */
class Status extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float cpu_percent = 1 [json_name = "cpuPercent"];</code>
     */
    protected $cpu_percent = 0.0;
    /**
     * Generated from protobuf field <code>int32 pid = 2 [json_name = "pid"];</code>
     */
    protected $pid = 0;
    /**
     * Generated from protobuf field <code>uint64 memory_usage = 3 [json_name = "memoryUsage"];</code>
     */
    protected $memory_usage = 0;
    /**
     * Generated from protobuf field <code>string command = 4 [json_name = "command"];</code>
     */
    protected $command = '';
    /**
     * error state
     *
     * Generated from protobuf field <code>.shared.v1.Status status = 5 [json_name = "status"];</code>
     */
    protected $status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $cpu_percent
     *     @type int $pid
     *     @type int|string $memory_usage
     *     @type string $command
     *     @type \RoadRunner\Shared\DTO\V1BETA1\Status $status
     *           error state
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Service\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float cpu_percent = 1 [json_name = "cpuPercent"];</code>
     * @return float
     */
    public function getCpuPercent()
    {
        return $this->cpu_percent;
    }

    /**
     * Generated from protobuf field <code>float cpu_percent = 1 [json_name = "cpuPercent"];</code>
     * @param float $var
     * @return $this
     */
    public function setCpuPercent($var)
    {
        GPBUtil::checkFloat($var);
        $this->cpu_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pid = 2 [json_name = "pid"];</code>
     * @return int
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * Generated from protobuf field <code>int32 pid = 2 [json_name = "pid"];</code>
     * @param int $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkInt32($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 memory_usage = 3 [json_name = "memoryUsage"];</code>
     * @return int|string
     */
    public function getMemoryUsage()
    {
        return $this->memory_usage;
    }

    /**
     * Generated from protobuf field <code>uint64 memory_usage = 3 [json_name = "memoryUsage"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemoryUsage($var)
    {
        GPBUtil::checkUint64($var);
        $this->memory_usage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string command = 4 [json_name = "command"];</code>
     * @return string
     */
    public function getCommand()
    {
        return $this->command;
    }

    /**
     * Generated from protobuf field <code>string command = 4 [json_name = "command"];</code>
     * @param string $var
     * @return $this
     */
    public function setCommand($var)
    {
        GPBUtil::checkString($var, True);
        $this->command = $var;

        return $this;
    }

    /**
     * error state
     *
     * Generated from protobuf field <code>.shared.v1.Status status = 5 [json_name = "status"];</code>
     * @return \RoadRunner\Shared\DTO\V1BETA1\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * error state
     *
     * Generated from protobuf field <code>.shared.v1.Status status = 5 [json_name = "status"];</code>
     * @param \RoadRunner\Shared\DTO\V1BETA1\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \RoadRunner\Shared\DTO\V1BETA1\Status::class);
        $this->status = $var;

        return $this;
    }

}

