<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv/v1/kv.proto

namespace RoadRunner\KV\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kv.v1.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     */
    protected $value = '';
    /**
     * RFC 3339
     *
     * Generated from protobuf field <code>string timeout = 3 [json_name = "timeout"];</code>
     */
    protected $timeout = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $value
     *     @type string $timeout
     *           RFC 3339
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\KV\DTO\V1\GPBMetadata\Kv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * RFC 3339
     *
     * Generated from protobuf field <code>string timeout = 3 [json_name = "timeout"];</code>
     * @return string
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * RFC 3339
     *
     * Generated from protobuf field <code>string timeout = 3 [json_name = "timeout"];</code>
     * @param string $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkString($var, True);
        $this->timeout = $var;

        return $this;
    }

}

