<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv/v1/kv.proto

namespace RoadRunner\KV\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * KV response for the KV RPC methods
 *
 * Generated from protobuf message <code>kv.v1.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .kv.v1.Item items = 1 [json_name = "items"];</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\RoadRunner\KV\DTO\V1\Item>|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\KV\DTO\V1\GPBMetadata\Kv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .kv.v1.Item items = 1 [json_name = "items"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .kv.v1.Item items = 1 [json_name = "items"];</code>
     * @param array<\RoadRunner\KV\DTO\V1\Item>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\KV\DTO\V1\Item::class);
        $this->items = $arr;

        return $this;
    }

}

