<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/v1/status.proto

namespace RoadRunner\Shared\DTO\V1BETA1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The `Status` type defines a logical error model that is suitable for
 * different programming environments, including REST APIs and RPC APIs.
 *
 * Generated from protobuf message <code>shared.v1.Status</code>
 */
class Status extends \Google\Protobuf\Internal\Message
{
    /**
     * A simple error code that can be easily handled by the client. The
     * actual error code is defined by `google.rpc.Code`.
     *
     * Generated from protobuf field <code>int32 code = 1 [json_name = "code"];</code>
     */
    protected $code = 0;
    /**
     * A developer-facing human-readable error message in English. It should
     * both explain the error and offer an actionable resolution to it.
     *
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     */
    protected $message = '';
    /**
     * Additional error information that the client code can use to handle
     * the error, such as retry info or a help link.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 3 [json_name = "details"];</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *           A simple error code that can be easily handled by the client. The
     *           actual error code is defined by `google.rpc.Code`.
     *     @type string $message
     *           A developer-facing human-readable error message in English. It should
     *           both explain the error and offer an actionable resolution to it.
     *     @type array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $details
     *           Additional error information that the client code can use to handle
     *           the error, such as retry info or a help link.
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Shared\DTO\V1BETA1\GPBMetadata\Status::initOnce();
        parent::__construct($data);
    }

    /**
     * A simple error code that can be easily handled by the client. The
     * actual error code is defined by `google.rpc.Code`.
     *
     * Generated from protobuf field <code>int32 code = 1 [json_name = "code"];</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * A simple error code that can be easily handled by the client. The
     * actual error code is defined by `google.rpc.Code`.
     *
     * Generated from protobuf field <code>int32 code = 1 [json_name = "code"];</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * A developer-facing human-readable error message in English. It should
     * both explain the error and offer an actionable resolution to it.
     *
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * A developer-facing human-readable error message in English. It should
     * both explain the error and offer an actionable resolution to it.
     *
     * Generated from protobuf field <code>string message = 2 [json_name = "message"];</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Additional error information that the client code can use to handle
     * the error, such as retry info or a help link.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 3 [json_name = "details"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Additional error information that the client code can use to handle
     * the error, such as retry info or a help link.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 3 [json_name = "details"];</code>
     * @param array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->details = $arr;

        return $this;
    }

}

