<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centrifugo/api/v1/api.proto

namespace RoadRunner\Centrifugal\API\DTO\V1;

if (false) {
    /**
     * This class is deprecated. Use RoadRunner\Centrifugal\API\DTO\V1\Command\MethodType instead.
     * @deprecated
     */
    class Command_MethodType {}
}
class_exists(Command\MethodType::class);
@trigger_error('RoadRunner\Centrifugal\API\DTO\V1\Command_MethodType is deprecated and will be removed in the next major release. Use RoadRunner\Centrifugal\API\DTO\V1\Command\MethodType instead', E_USER_DEPRECATED);

