<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centrifugo/api/v1/api.proto

namespace RoadRunner\Centrifugal\API\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.api.InvalidateUserTokensRequest</code>
 */
class InvalidateUserTokensRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 expire_at = 1 [json_name = "expireAt"];</code>
     */
    protected $expire_at = 0;
    /**
     * Generated from protobuf field <code>string user = 2 [json_name = "user"];</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>int64 issued_before = 3 [json_name = "issuedBefore"];</code>
     */
    protected $issued_before = 0;
    /**
     * Generated from protobuf field <code>string channel = 4 [json_name = "channel"];</code>
     */
    protected $channel = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $expire_at
     *     @type string $user
     *     @type int|string $issued_before
     *     @type string $channel
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\API\DTO\V1\GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 expire_at = 1 [json_name = "expireAt"];</code>
     * @return int|string
     */
    public function getExpireAt()
    {
        return $this->expire_at;
    }

    /**
     * Generated from protobuf field <code>int64 expire_at = 1 [json_name = "expireAt"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 2 [json_name = "user"];</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 2 [json_name = "user"];</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 issued_before = 3 [json_name = "issuedBefore"];</code>
     * @return int|string
     */
    public function getIssuedBefore()
    {
        return $this->issued_before;
    }

    /**
     * Generated from protobuf field <code>int64 issued_before = 3 [json_name = "issuedBefore"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setIssuedBefore($var)
    {
        GPBUtil::checkInt64($var);
        $this->issued_before = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel = 4 [json_name = "channel"];</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 4 [json_name = "channel"];</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

}

