<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centrifugo/api/v1/api.proto

namespace RoadRunner\Centrifugal\API\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.api.Process</code>
 */
class Process extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double cpu = 1 [json_name = "cpu"];</code>
     */
    protected $cpu = 0.0;
    /**
     * Generated from protobuf field <code>int64 rss = 2 [json_name = "rss"];</code>
     */
    protected $rss = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $cpu
     *     @type int|string $rss
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\API\DTO\V1\GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double cpu = 1 [json_name = "cpu"];</code>
     * @return float
     */
    public function getCpu()
    {
        return $this->cpu;
    }

    /**
     * Generated from protobuf field <code>double cpu = 1 [json_name = "cpu"];</code>
     * @param float $var
     * @return $this
     */
    public function setCpu($var)
    {
        GPBUtil::checkDouble($var);
        $this->cpu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 rss = 2 [json_name = "rss"];</code>
     * @return int|string
     */
    public function getRss()
    {
        return $this->rss;
    }

    /**
     * Generated from protobuf field <code>int64 rss = 2 [json_name = "rss"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRss($var)
    {
        GPBUtil::checkInt64($var);
        $this->rss = $var;

        return $this;
    }

}

