<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centrifugo/api/v1/api.proto

namespace RoadRunner\Centrifugal\API\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.api.Publication</code>
 */
class Publication extends \Google\Protobuf\Internal\Message
{
    /**
     * Removed: string uid = 1;
     *
     * Generated from protobuf field <code>bytes data = 2 [json_name = "data"];</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.ClientInfo info = 3 [json_name = "info"];</code>
     */
    protected $info = null;
    /**
     * Generated from protobuf field <code>uint64 offset = 4 [json_name = "offset"];</code>
     */
    protected $offset = 0;
    /**
     * Generated from protobuf field <code>map<string, string> tags = 5 [json_name = "tags"];</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $data
     *           Removed: string uid = 1;
     *     @type \RoadRunner\Centrifugal\API\DTO\V1\ClientInfo $info
     *     @type int|string $offset
     *     @type array|\Google\Protobuf\Internal\MapField $tags
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\API\DTO\V1\GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Removed: string uid = 1;
     *
     * Generated from protobuf field <code>bytes data = 2 [json_name = "data"];</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Removed: string uid = 1;
     *
     * Generated from protobuf field <code>bytes data = 2 [json_name = "data"];</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.ClientInfo info = 3 [json_name = "info"];</code>
     * @return \RoadRunner\Centrifugal\API\DTO\V1\ClientInfo|null
     */
    public function getInfo()
    {
        return $this->info;
    }

    public function hasInfo()
    {
        return isset($this->info);
    }

    public function clearInfo()
    {
        unset($this->info);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.ClientInfo info = 3 [json_name = "info"];</code>
     * @param \RoadRunner\Centrifugal\API\DTO\V1\ClientInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \RoadRunner\Centrifugal\API\DTO\V1\ClientInfo::class);
        $this->info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 offset = 4 [json_name = "offset"];</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>uint64 offset = 4 [json_name = "offset"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkUint64($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 5 [json_name = "tags"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 5 [json_name = "tags"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

