<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobs/v1/jobs.proto

namespace RoadRunner\Jobs\DTO\V1\GPBMetadata;

class Jobs
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
î	
jobs/v1/jobs.protojobs.v1"-
PushRequest
job (2.jobs.v1.JobRjob"4
PushBatchRequest 
jobs (2.jobs.v1.JobRjobs"Ù
Job
job (	Rjob
id (	Rid
payload (	Rpayload3
headers (2.jobs.v1.Job.HeadersEntryRheaders*
options (2.jobs.v1.OptionsRoptionsP
HeadersEntry
key (	Rkey*
value (2.jobs.v1.HeaderValueRvalue:8"⁄
Options
priority (Rpriority
pipeline (	Rpipeline
delay (Rdelay
auto_ack (RautoAck
topic (	Rtopic
metadata (	Rmetadata
offset	 (Roffset
	partition
 (R	partition"#
HeaderValue
value (	Rvalue"ê
DeclareRequestA
pipeline (2%.jobs.v1.DeclareRequest.PipelineEntryRpipeline;
PipelineEntry
key (	Rkey
value (	Rvalue:8",
Stats#
stats (2.jobs.v1.StatRstats"–
Stat
pipeline (	Rpipeline
driver (	Rdriver
queue (	Rqueue
active (Ractive
delayed (Rdelayed
reserved (Rreserved
ready (Rready
priority (Rpriority")
	Pipelines
	pipelines (	R	pipelines"
EmptyBGZjobs/v1 RoadRunner\\Jobs\\DTO\\V1‚"RoadRunner\\Jobs\\DTO\\V1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

