<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/v1/service.proto

namespace RoadRunner\Service\DTO\V1\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\Shared\DTO\V1BETA1\GPBMetadata\Status::initOnce();
        $pool->internalAddGeneratedFile(
            '
ˆ
service/v1/service.proto
service.v1"4
Response
message (	Rmessage
ok (Rok"®
Create
name (	Rname
command (	Rcommand
process_num (R
processNum!
exec_timeout (RexecTimeout*
remain_after_exit (RremainAfterExit-
env (2.service.v1.Create.EnvEntryRenv
restart_sec (R
restartSec6
EnvEntry
key (	Rkey
value (	Rvalue:8"6
Statuses*
status (2.service.v1.StatusRstatus"£
Status
cpu_percent (R
cpuPercent
pid (Rpid!
memory_usage (RmemoryUsage
command (	Rcommand)
status (2.shared.v1.StatusRstatus"
Service
name (	Rname""
List
services (	RservicesBPZ
service/v1ÊRoadRunner\\Service\\DTO\\V1â%RoadRunner\\Service\\DTO\\V1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

