<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv/v1/kv.proto

namespace RoadRunner\KV\DTO\V1\GPBMetadata;

class Kv
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
£
kv/v1/kv.protokv.v1"F
Request
storage (	Rstorage!
items (2.kv.v1.ItemRitems"H
Item
key (	Rkey
value (Rvalue
timeout (	Rtimeout"-
Response!
items (2.kv.v1.ItemRitemsBAZkv/v1ÊRoadRunner\\KV\\DTO\\V1â RoadRunner\\KV\\DTO\\V1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

