<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: websockets/v1/websockets.proto

namespace RoadRunner\Websockets\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RPC response (false in case of error)
 *
 * Generated from protobuf message <code>websockets.v1.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool ok = 1 [json_name = "ok"];</code>
     */
    protected $ok = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $ok
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Websockets\DTO\V1\GPBMetadata\Websockets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool ok = 1 [json_name = "ok"];</code>
     * @return bool
     */
    public function getOk()
    {
        return $this->ok;
    }

    /**
     * Generated from protobuf field <code>bool ok = 1 [json_name = "ok"];</code>
     * @param bool $var
     * @return $this
     */
    public function setOk($var)
    {
        GPBUtil::checkBool($var);
        $this->ok = $var;

        return $this;
    }

}

