<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/v1/status.proto

namespace RoadRunner\Shared\DTO\V1BETA1\GPBMetadata;

class Status
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            '
ì
shared/v1/status.proto	shared.v1"f
Status
code (Rcode
message (	Rmessage.
details (2.google.protobuf.AnyRdetailsBWZ	status/v1ÊRoadRunner\\Shared\\DTO\\V1BETA1â)RoadRunner\\Shared\\DTO\\V1BETA1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

