<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http/v1beta/http.proto

namespace RoadRunner\HTTP\DTO\V1BETA1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>http.v1beta.FileUpload</code>
 */
class FileUpload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string mime = 2 [json_name = "mime"];</code>
     */
    protected $mime = '';
    /**
     * Generated from protobuf field <code>int64 size = 3 [json_name = "size"];</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>int64 error = 4 [json_name = "error"];</code>
     */
    protected $error = 0;
    /**
     * Generated from protobuf field <code>string temp_filename = 5 [json_name = "tempFilename"];</code>
     */
    protected $temp_filename = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Any header = 9 [json_name = "header"];</code>
     */
    protected $header = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $mime
     *     @type int|string $size
     *     @type int|string $error
     *     @type string $temp_filename
     *     @type \Google\Protobuf\Any $header
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\HTTP\DTO\V1BETA1\GPBMetadata\Http::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mime = 2 [json_name = "mime"];</code>
     * @return string
     */
    public function getMime()
    {
        return $this->mime;
    }

    /**
     * Generated from protobuf field <code>string mime = 2 [json_name = "mime"];</code>
     * @param string $var
     * @return $this
     */
    public function setMime($var)
    {
        GPBUtil::checkString($var, True);
        $this->mime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 size = 3 [json_name = "size"];</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>int64 size = 3 [json_name = "size"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 error = 4 [json_name = "error"];</code>
     * @return int|string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>int64 error = 4 [json_name = "error"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkInt64($var);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string temp_filename = 5 [json_name = "tempFilename"];</code>
     * @return string
     */
    public function getTempFilename()
    {
        return $this->temp_filename;
    }

    /**
     * Generated from protobuf field <code>string temp_filename = 5 [json_name = "tempFilename"];</code>
     * @param string $var
     * @return $this
     */
    public function setTempFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->temp_filename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any header = 9 [json_name = "header"];</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any header = 9 [json_name = "header"];</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->header = $var;

        return $this;
    }

}

