<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http/v1beta/http.proto

namespace RoadRunner\HTTP\DTO\V1BETA1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>http.v1beta.HeaderValue</code>
 */
class HeaderValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string value = 1 [json_name = "value"];</code>
     */
    private $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $value
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\HTTP\DTO\V1BETA1\GPBMetadata\Http::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string value = 1 [json_name = "value"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>repeated string value = 1 [json_name = "value"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->value = $arr;

        return $this;
    }

}

