<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http/v1beta/http.proto

namespace RoadRunner\HTTP\DTO\V1BETA1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>http.v1beta.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string remote_addr = 1 [json_name = "remoteAddr"];</code>
     */
    protected $remote_addr = '';
    /**
     * Generated from protobuf field <code>string protocol = 2 [json_name = "protocol"];</code>
     */
    protected $protocol = '';
    /**
     * Generated from protobuf field <code>string method = 3 [json_name = "method"];</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>string uri = 4 [json_name = "uri"];</code>
     */
    protected $uri = '';
    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> header = 5 [json_name = "header"];</code>
     */
    private $header;
    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> cookies = 6 [json_name = "cookies"];</code>
     */
    private $cookies;
    /**
     * Generated from protobuf field <code>string raw_query = 7 [json_name = "rawQuery"];</code>
     */
    protected $raw_query = '';
    /**
     * Generated from protobuf field <code>bool parsed = 8 [json_name = "parsed"];</code>
     */
    protected $parsed = false;
    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> attributes = 9 [json_name = "attributes"];</code>
     */
    private $attributes;
    /**
     * Generated from protobuf field <code>.http.v1beta.Uploads uploads = 10 [json_name = "uploads"];</code>
     */
    protected $uploads = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $remote_addr
     *     @type string $protocol
     *     @type string $method
     *     @type string $uri
     *     @type array|\Google\Protobuf\Internal\MapField $header
     *     @type array|\Google\Protobuf\Internal\MapField $cookies
     *     @type string $raw_query
     *     @type bool $parsed
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *     @type \RoadRunner\HTTP\DTO\V1BETA1\Uploads $uploads
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\HTTP\DTO\V1BETA1\GPBMetadata\Http::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string remote_addr = 1 [json_name = "remoteAddr"];</code>
     * @return string
     */
    public function getRemoteAddr()
    {
        return $this->remote_addr;
    }

    /**
     * Generated from protobuf field <code>string remote_addr = 1 [json_name = "remoteAddr"];</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->remote_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protocol = 2 [json_name = "protocol"];</code>
     * @return string
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>string protocol = 2 [json_name = "protocol"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkString($var, True);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 3 [json_name = "method"];</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 3 [json_name = "method"];</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uri = 4 [json_name = "uri"];</code>
     * @return string
     */
    public function getUri()
    {
        return $this->uri;
    }

    /**
     * Generated from protobuf field <code>string uri = 4 [json_name = "uri"];</code>
     * @param string $var
     * @return $this
     */
    public function setUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> header = 5 [json_name = "header"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> header = 5 [json_name = "header"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\HTTP\DTO\V1BETA1\HeaderValue::class);
        $this->header = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> cookies = 6 [json_name = "cookies"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCookies()
    {
        return $this->cookies;
    }

    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> cookies = 6 [json_name = "cookies"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCookies($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\HTTP\DTO\V1BETA1\HeaderValue::class);
        $this->cookies = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string raw_query = 7 [json_name = "rawQuery"];</code>
     * @return string
     */
    public function getRawQuery()
    {
        return $this->raw_query;
    }

    /**
     * Generated from protobuf field <code>string raw_query = 7 [json_name = "rawQuery"];</code>
     * @param string $var
     * @return $this
     */
    public function setRawQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->raw_query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool parsed = 8 [json_name = "parsed"];</code>
     * @return bool
     */
    public function getParsed()
    {
        return $this->parsed;
    }

    /**
     * Generated from protobuf field <code>bool parsed = 8 [json_name = "parsed"];</code>
     * @param bool $var
     * @return $this
     */
    public function setParsed($var)
    {
        GPBUtil::checkBool($var);
        $this->parsed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> attributes = 9 [json_name = "attributes"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, .http.v1beta.HeaderValue> attributes = 9 [json_name = "attributes"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\HTTP\DTO\V1BETA1\HeaderValue::class);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.http.v1beta.Uploads uploads = 10 [json_name = "uploads"];</code>
     * @return \RoadRunner\HTTP\DTO\V1BETA1\Uploads|null
     */
    public function getUploads()
    {
        return $this->uploads;
    }

    public function hasUploads()
    {
        return isset($this->uploads);
    }

    public function clearUploads()
    {
        unset($this->uploads);
    }

    /**
     * Generated from protobuf field <code>.http.v1beta.Uploads uploads = 10 [json_name = "uploads"];</code>
     * @param \RoadRunner\HTTP\DTO\V1BETA1\Uploads $var
     * @return $this
     */
    public function setUploads($var)
    {
        GPBUtil::checkMessage($var, \RoadRunner\HTTP\DTO\V1BETA1\Uploads::class);
        $this->uploads = $var;

        return $this;
    }

}

