<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http/v1beta/http.proto

namespace RoadRunner\HTTP\DTO\V1BETA1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>http.v1beta.Uploads</code>
 */
class Uploads extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .http.v1beta.FileUpload list = 1 [json_name = "list"];</code>
     */
    private $list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\RoadRunner\HTTP\DTO\V1BETA1\FileUpload>|\Google\Protobuf\Internal\RepeatedField $list
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\HTTP\DTO\V1BETA1\GPBMetadata\Http::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .http.v1beta.FileUpload list = 1 [json_name = "list"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .http.v1beta.FileUpload list = 1 [json_name = "list"];</code>
     * @param array<\RoadRunner\HTTP\DTO\V1BETA1\FileUpload>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\HTTP\DTO\V1BETA1\FileUpload::class);
        $this->list = $arr;

        return $this;
    }

}

