<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centrifugo/proxy/v1/proxy.proto

namespace RoadRunner\Centrifugal\Proxy\DTO\V1\GPBMetadata;

class Proxy
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
°\'
centrifugo/proxy/v1/proxy.protocentrifugal.centrifugo.proxy"V

Disconnect
code (Rcode
reason (	Rreason
	reconnect (R	reconnect"S
Error
code (Rcode
message (	Rmessage
	temporary (R	temporary"ö
ConnectRequest
client (	Rclient
	transport (	R	transport
protocol (	Rprotocol
encoding (	Rencoding
data
 (Rdata
b64data (	Rb64data
name (	Rname
version (	Rversion
channels (	Rchannels"Þ
SubscribeOptions
	expire_at (RexpireAt
info (Rinfo
b64info (	Rb64info
data (Rdata
b64data (	Rb64dataQ
override (25.centrifugal.centrifugo.proxy.SubscribeOptionOverrideRoverride"Æ
ConnectResult
user (	Ruser
	expire_at (RexpireAt
info (Rinfo
b64info (	Rb64info
data (Rdata
b64data (	Rb64data
channels (	RchannelsI
subs (25.centrifugal.centrifugo.proxy.ConnectResult.SubsEntryRsubs
meta	 (RmetaD
caps
 (20.centrifugal.centrifugo.proxy.ChannelsCapabilityRcapsg
	SubsEntry
key (	RkeyD
value (2..centrifugal.centrifugo.proxy.SubscribeOptionsRvalue:8"\\
ChannelsCapability
channels (	Rchannels
allow (	Rallow
match (	Rmatch"Û
ConnectResponseC
result (2+.centrifugal.centrifugo.proxy.ConnectResultRresult9
error (2#.centrifugal.centrifugo.proxy.ErrorRerrorH

disconnect (2(.centrifugal.centrifugo.proxy.DisconnectR
disconnect"¦
RefreshRequest
client (	Rclient
	transport (	R	transport
protocol (	Rprotocol
encoding (	Rencoding
user
 (	Ruser
meta (Rmeta"Î
RefreshResult
expired (Rexpired
	expire_at (RexpireAt
info (Rinfo
b64info (	Rb64info
meta (RmetaD
caps (20.centrifugal.centrifugo.proxy.ChannelsCapabilityRcaps"Û
RefreshResponseC
result (2+.centrifugal.centrifugo.proxy.RefreshResultRresult9
error (2#.centrifugal.centrifugo.proxy.ErrorRerrorH

disconnect (2(.centrifugal.centrifugo.proxy.DisconnectR
disconnect"†
SubscribeRequest
client (	Rclient
	transport (	R	transport
protocol (	Rprotocol
encoding (	Rencoding
user
 (	Ruser
channel (	Rchannel
token (	Rtoken
meta (Rmeta
data (Rdata
b64data (	Rb64data"!
	BoolValue
value (Rvalue""

Int32Value
value (Rvalue"¨
SubscribeOptionOverrideC
presence (2\'.centrifugal.centrifugo.proxy.BoolValueRpresenceF

join_leave (2\'.centrifugal.centrifugo.proxy.BoolValueR	joinLeaveN
force_recovery (2\'.centrifugal.centrifugo.proxy.BoolValueRforceRecoveryT
force_positioning (2\'.centrifugal.centrifugo.proxy.BoolValueRforcePositioningZ
force_push_join_leave (2\'.centrifugal.centrifugo.proxy.BoolValueRforcePushJoinLeave"ó
SubscribeResult
	expire_at (RexpireAt
info (Rinfo
b64info (	Rb64info
data (Rdata
b64data (	Rb64dataQ
override (25.centrifugal.centrifugo.proxy.SubscribeOptionOverrideRoverride
allow (	Rallow"ß
SubscribeResponseE
result (2-.centrifugal.centrifugo.proxy.SubscribeResultRresult9
error (2#.centrifugal.centrifugo.proxy.ErrorRerrorH

disconnect (2(.centrifugal.centrifugo.proxy.DisconnectR
disconnect"î
PublishRequest
client (	Rclient
	transport (	R	transport
protocol (	Rprotocol
encoding (	Rencoding
user
 (	Ruser
channel (	Rchannel
data (Rdata
b64data (	Rb64data
meta (Rmeta"`
PublishResult
data (Rdata
b64data (	Rb64data!
skip_history (RskipHistory"Û
PublishResponseC
result (2+.centrifugal.centrifugo.proxy.PublishResultRresult9
error (2#.centrifugal.centrifugo.proxy.ErrorRerrorH

disconnect (2(.centrifugal.centrifugo.proxy.DisconnectR
disconnect"è

RPCRequest
client (	Rclient
	transport (	R	transport
protocol (	Rprotocol
encoding (	Rencoding
user
 (	Ruser
method (	Rmethod
data (Rdata
b64data (	Rb64data
meta (Rmeta"9
	RPCResult
data (Rdata
b64data (	Rb64data"Ó
RPCResponse?
result (2\'.centrifugal.centrifugo.proxy.RPCResultRresult9
error (2#.centrifugal.centrifugo.proxy.ErrorRerrorH

disconnect (2(.centrifugal.centrifugo.proxy.DisconnectR
disconnect2“
CentrifugoProxyf
Connect,.centrifugal.centrifugo.proxy.ConnectRequest-.centrifugal.centrifugo.proxy.ConnectResponsef
Refresh,.centrifugal.centrifugo.proxy.RefreshRequest-.centrifugal.centrifugo.proxy.RefreshResponsel
	Subscribe..centrifugal.centrifugo.proxy.SubscribeRequest/.centrifugal.centrifugo.proxy.SubscribeResponsef
Publish,.centrifugal.centrifugo.proxy.PublishRequest-.centrifugal.centrifugo.proxy.PublishResponseZ
RPC(.centrifugal.centrifugo.proxy.RPCRequest).centrifugal.centrifugo.proxy.RPCResponseBmZcentrifugo/proxy/v1Ê#RoadRunner\\Centrifugal\\Proxy\\DTO\\V1â/RoadRunner\\Centrifugal\\Proxy\\DTO\\V1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

