<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: websockets/v1/websockets.proto

namespace RoadRunner\Websockets\DTO\V1\GPBMetadata;

class Websockets
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ä
websockets/v1/websockets.protowebsockets.v1"U
Message
command (	Rcommand
topics (	Rtopics
payload (Rpayload"=
Request2
messages (2.websockets.v1.MessageRmessages"
Response
ok (RokBYZwebsockets/v1ÊRoadRunner\\Websockets\\DTO\\V1â(RoadRunner\\Websockets\\DTO\\V1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

