name: 'Buf Lint'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: 'buf lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint protofiles
        run: buf lint
