name: Linters

on: [push, pull_request]

jobs:
  golangci-lint:
    name: Golang-CI (lint)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: 1.19

      - name: Run linter
        uses: golangci/golangci-lint-action@v3.2.0 # Action page: <https://github.com/golangci/golangci-lint-action>
        with:
          version: v1.48 # without patch version
          only-new-issues: false # show only new issues if it's a pull request
          args: --timeout=10m --build-tags=race
